name: 'Javaherian & Ruszecki | A Professional Law Corporation'
favicon: null
layout_spectrum: 0.8565453477203846
typography_spectrum: 0.5297379218973219
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.16155862086452544
  lightness: 0.7984799083787948
  saturation: 0.587862356333062
  rhythmicContrast: 0.3374140018131584
purpose: []
